# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('por_sesion', 'Por sesión')], max_length=20)),
                ('duracion_dias', models.SmallIntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requiere_entrenador', models.BooleanField(db_default=False)),
                ('activo', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
            ],
            options={
                'db_table': 'planes',
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(help_text='Se calcula en la aplicación como fecha_inicio + planes.duracion_dias. No es columna generada porque duracion_dias vive en otra tabla.')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], db_default='activa', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='clientes.cliente')),
                ('entrenador', models.ForeignKey(blank=True, db_column='entrenador_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membresias_como_entrenador', to=settings.AUTH_USER_MODEL)),
                ('membresia_anterior', models.ForeignKey(blank=True, db_column='membresia_anterior_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renovaciones', to='membresias.membresia')),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='organizacion.sede')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='plataforma.tenant')),
                ('vendedor', models.ForeignKey(db_column='vendedor_id', on_delete=django.db.models.deletion.PROTECT, related_name='membresias_vendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membresias',
            },
        ),
    ]
