# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('plataforma', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='venta',
            field=models.ForeignKey(blank=True, db_column='venta_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='plan',
            name='sede',
            field=models.ForeignKey(blank=True, db_column='sede_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='organizacion.sede'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='plataforma.tenant'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='plan',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='membresias.plan'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_planes_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uq_planes_nombre'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='ck_planes_precio'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duracion_dias__isnull', True), ('tipo', 'por_sesion')), models.Q(models.Q(('tipo', 'por_sesion'), _negated=True), ('duracion_dias__gt', 0)), _connector='OR'), name='ck_planes_duracion'),
        ),
        migrations.AddIndex(
            model_name='membresia',
            index=models.Index(condition=models.Q(('estado', 'activa')), fields=['cliente', '-fecha_fin'], name='ix_membresias_cliente_vigencia'),
        ),
        migrations.AddIndex(
            model_name='membresia',
            index=models.Index(condition=models.Q(('estado', 'activa')), fields=['tenant', 'sede', 'fecha_fin'], name='ix_membresias_vencimiento'),
        ),
        migrations.AddIndex(
            model_name='membresia',
            index=models.Index(condition=models.Q(('entrenador__isnull', False), ('estado', 'activa')), fields=['entrenador', '-fecha_fin'], name='ix_membresias_entrenador'),
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_membresias_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='ck_membresias_fechas'),
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.CheckConstraint(condition=models.Q(('precio_pagado__gte', 0)), name='ck_membresias_precio'),
        ),
        migrations.AddConstraint(
            model_name='membresia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'cancelada'), _negated=True), ('motivo_cancelacion__isnull', False), _connector='OR'), name='ck_membresias_cancel'),
        ),
    ]
