# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        ('membresias', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('activa', models.BooleanField(db_default=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='categorias_gasto', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'categorias_gasto',
            },
        ),
        migrations.CreateModel(
            name='CategoriaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('subcategoria', models.CharField(blank=True, max_length=80, null=True)),
                ('es_sistema', models.BooleanField(db_default=False)),
                ('activa', models.BooleanField(db_default=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='categorias_ingreso', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'categorias_ingreso',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('descripcion', models.CharField(max_length=250)),
                ('comprobante_url', models.TextField(blank=True, null=True)),
                ('es_recurrente', models.BooleanField(db_default=False)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('categoria_gasto', models.ForeignKey(db_column='categoria_gasto_id', on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='ventas.categoriagasto')),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='organizacion.sede')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='plataforma.tenant')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gastos',
            },
        ),
        migrations.CreateModel(
            name='IngresoOtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('categoria_ingreso', models.ForeignKey(db_column='categoria_ingreso_id', on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_otros', to='ventas.categoriaingreso')),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_otros', to='organizacion.sede')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_otros', to='plataforma.tenant')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_otros_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ingresos_otros',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.BigIntegerField()),
                ('fecha_hora', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(db_default=0, decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo_descuento', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('pagada', 'Pagada'), ('parcial', 'Parcial'), ('pendiente', 'Pendiente'), ('anulada', 'Anulada')], db_default='pagada', max_length=20)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('anulada_por', models.ForeignKey(blank=True, db_column='anulada_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_anuladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente')),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='organizacion.sede')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='plataforma.tenant')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('es_pago_inicial', models.BooleanField(db_default=False)),
                ('fecha_hora', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('anulado', models.BooleanField(db_default=False)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='plataforma.tenant')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('producto', 'Producto'), ('plan', 'Plan')], max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(db_default=0, decimal_places=2, max_digits=12)),
                ('total_linea', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('cantidad'), '*', models.F('precio_unitario')), output_field=models.DecimalField(decimal_places=2, max_digits=12))),
                ('categoria_ingreso', models.ForeignKey(db_column='categoria_ingreso_id', on_delete=django.db.models.deletion.PROTECT, related_name='detalle_ventas', to='ventas.categoriaingreso')),
                ('plan', models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_ventas', to='membresias.plan')),
                ('producto', models.ForeignKey(blank=True, db_column='producto_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_ventas', to='inventario.producto')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalle_ventas', to='plataforma.tenant')),
                ('venta', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'db_table': 'detalle_ventas',
            },
        ),
        migrations.AddConstraint(
            model_name='categoriagasto',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_catgasto_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='categoriagasto',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uq_catgasto_nombre'),
        ),
        migrations.AddConstraint(
            model_name='categoriaingreso',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_catingr_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='categoriaingreso',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre', 'subcategoria'), name='uq_catingr_nombre'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['sede', '-fecha'], name='ix_gastos_sede_fecha'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['tenant', 'categoria_gasto', '-fecha'], name='ix_gastos_categoria'),
        ),
        migrations.AddConstraint(
            model_name='gasto',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_gastos_monto'),
        ),
        migrations.AddIndex(
            model_name='ingresootro',
            index=models.Index(fields=['sede', '-fecha'], name='ix_ingotros_sede_fecha'),
        ),
        migrations.AddConstraint(
            model_name='ingresootro',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_ingotros_monto'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(condition=models.Q(('estado', 'anulada'), _negated=True), fields=['sede', '-fecha_hora'], name='ix_ventas_sede_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(condition=models.Q(('cliente__isnull', False)), fields=['cliente', '-fecha_hora'], name='ix_ventas_cliente'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(condition=models.Q(('estado__in', ['parcial', 'pendiente'])), fields=['tenant', 'cliente'], name='ix_ventas_cartera'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['tenant', '-fecha_hora'], name='ix_ventas_tenant_fecha'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_ventas_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('sede', 'consecutivo'), name='uq_ventas_consecutivo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('descuento__gte', 0), ('descuento__lte', models.F('subtotal')), ('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('descuento')))), name='ck_ventas_montos'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('descuento', 0), models.Q(('motivo_descuento__isnull', False), models.Q(('motivo_descuento__regex', '^\\s*$'), _negated=True)), _connector='OR'), name='ck_ventas_descuento'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ['parcial', 'pendiente']), _negated=True), ('cliente__isnull', False), _connector='OR'), name='ck_ventas_credito'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anulada_en__isnull', False), ('anulada_por__isnull', False), ('estado', 'anulada'), ('motivo_anulacion__isnull', False)), models.Q(models.Q(('estado', 'anulada'), _negated=True), ('anulada_en__isnull', True), ('anulada_por__isnull', True), ('motivo_anulacion__isnull', True)), _connector='OR'), name='ck_ventas_anulacion'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['venta', 'fecha_hora'], name='ix_pagos_venta'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(condition=models.Q(('anulado', True), _negated=True), fields=['tenant', '-fecha_hora'], name='ix_pagos_tenant_fecha'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_pagos_monto'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['venta'], name='ix_detven_venta'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(condition=models.Q(('producto__isnull', False)), fields=['producto'], name='ix_detven_producto'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['tenant', 'categoria_ingreso'], name='ix_detven_categoria'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_detven_cantidad'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('costo_unitario__gte', 0), ('precio_unitario__gte', 0)), name='ck_detven_precio'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plan__isnull', True), ('producto__isnull', False), ('tipo_item', 'producto')), models.Q(('plan__isnull', False), ('producto__isnull', True), ('tipo_item', 'plan')), _connector='OR'), name='ck_detven_item'),
        ),
    ]
