# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoBiometricoFallido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad_captura', models.SmallIntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
            ],
            options={
                'db_table': 'intentos_biometricos_fallidos',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('huella', 'Huella'), ('manual_cedula', 'Manual por cédula'), ('sesion_anonima', 'Sesión anónima')], max_length=20)),
                ('fecha_hora', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('con_membresia_vigente', models.BooleanField()),
                ('motivo_autorizacion', models.TextField(blank=True, null=True)),
                ('registrado_offline', models.BooleanField(db_default=False)),
                ('sincronizado_en', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, db_column='autorizado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='clientes.cliente')),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='organizacion.sede')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'asistencias',
            },
        ),
    ]
