# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('clientes', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('plataforma', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='venta',
            field=models.ForeignKey(blank=True, db_column='venta_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='intentobiometricofallido',
            name='dispositivo',
            field=models.ForeignKey(blank=True, db_column='dispositivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_fallidos', to='clientes.dispositivobiometrico'),
        ),
        migrations.AddField(
            model_name='intentobiometricofallido',
            name='sede',
            field=models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, related_name='intentos_biometricos_fallidos', to='organizacion.sede'),
        ),
        migrations.AddField(
            model_name='intentobiometricofallido',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='intentos_biometricos_fallidos', to='plataforma.tenant'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(condition=models.Q(('cliente__isnull', False)), fields=['cliente', '-fecha_hora'], name='ix_asist_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['sede', '-fecha_hora'], name='ix_asist_sede_fecha'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', True), ('metodo', 'sesion_anonima'), ('venta__isnull', False)), models.Q(models.Q(('metodo', 'sesion_anonima'), _negated=True), ('cliente__isnull', False)), _connector='OR'), name='ck_asist_anonima'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.CheckConstraint(condition=models.Q(('con_membresia_vigente', True), ('metodo', 'sesion_anonima'), models.Q(('autorizado_por__isnull', False), ('motivo_autorizacion__isnull', False)), _connector='OR'), name='ck_asist_autorizacion'),
        ),
        migrations.AddIndex(
            model_name='intentobiometricofallido',
            index=models.Index(fields=['sede', '-fecha_hora'], name='ix_intfall_sede_fecha'),
        ),
    ]
