# Generated by Django 6.0.7 on 2026-07-30 03:27

import apps.organizacion.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('modulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('nit', models.CharField(blank=True, max_length=30, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('encabezado_recibo', models.TextField(blank=True, null=True)),
                ('prefijo_comprobante', models.CharField(db_default='F', max_length=10)),
                ('activa', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'sedes',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('es_sistema', models.BooleanField(db_default=False)),
                ('activo', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=254)),
                ('password', models.TextField(db_column='password_hash')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(db_default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acceso', null=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='plataforma.tenant')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='organizacion.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', apps.organizacion.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('pk', models.CompositePrimaryKey('rol', 'permiso', blank=True, editable=False, primary_key=True, serialize=False)),
                ('permiso', models.ForeignKey(db_column='permiso_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='organizacion.permiso')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='organizacion.rol')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'roles_permisos',
            },
        ),
        migrations.CreateModel(
            name='SecuenciaComprobante',
            fields=[
                ('sede', models.OneToOneField(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='secuencia_comprobante', serialize=False, to='organizacion.sede')),
                ('ultimo_numero', models.BigIntegerField(db_default=0)),
            ],
            options={
                'db_table': 'secuencias_comprobantes',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSede',
            fields=[
                ('pk', models.CompositePrimaryKey('usuario', 'sede', blank=True, editable=False, primary_key=True, serialize=False)),
                ('asignado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_sedes', to='organizacion.sede')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_sedes', to='plataforma.tenant')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_sedes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_sedes',
            },
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_roles_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uq_roles_nombre'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(condition=models.Q(('activo', True)), fields=['tenant'], name='ix_usuarios_tenant'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_usuarios_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('correo'), models.F('tenant'), name='uq_usuarios_correo'),
        ),
        migrations.AddIndex(
            model_name='rolpermiso',
            index=models.Index(fields=['permiso'], name='ix_rolperm_permiso'),
        ),
        migrations.AddField(
            model_name='secuenciacomprobante',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='secuencias_comprobantes', to='plataforma.tenant'),
        ),
        migrations.AddIndex(
            model_name='sede',
            index=models.Index(condition=models.Q(('activa', True)), fields=['tenant'], name='ix_sedes_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sede',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_sedes_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sede',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uq_sedes_nombre'),
        ),
        migrations.AddIndex(
            model_name='usuariosede',
            index=models.Index(fields=['sede'], name='ix_usrsede_sede'),
        ),
        migrations.AddConstraint(
            model_name='secuenciacomprobante',
            constraint=models.CheckConstraint(condition=models.Q(('ultimo_numero__gte', 0)), name='ck_secuencias_numero'),
        ),
    ]
