# Generated by Django 6.0.7 on 2026-07-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_staff',
            field=models.BooleanField(db_default=False, help_text='Acceso al panel de administración de Django. NO es lo mismo que ser administrador del gimnasio: se concede explícitamente.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_superusuario',
            field=models.BooleanField(db_default=False),
        ),
    ]
