# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_inicio', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('estatura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('activa', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='fichas_medidas', to='clientes.cliente')),
                ('entrenador', models.ForeignKey(db_column='entrenador_id', on_delete=django.db.models.deletion.PROTECT, related_name='fichas_medidas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='fichas_medidas', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'fichas_medidas',
            },
        ),
        migrations.CreateModel(
            name='ControlMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.SmallIntegerField()),
                ('fecha', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cuello', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hombros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pecho_espalda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brazos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('antebrazos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('muneca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cadera_gluteos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('piernas_media', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rodillas_arriba', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pantorrillas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tobillos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('registrado_por', models.ForeignKey(db_column='registrado_por', on_delete=django.db.models.deletion.PROTECT, related_name='controles_medidas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='controles_medidas', to='plataforma.tenant')),
                ('ficha_medida', models.ForeignKey(db_column='ficha_medida_id', on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='entrenamiento.fichamedidas')),
            ],
            options={
                'db_table': 'controles_medidas',
            },
        ),
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.SmallIntegerField(db_default=0)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_musculares', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'grupos_musculares',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='plataforma.tenant')),
                ('grupo_muscular', models.ForeignKey(db_column='grupo_muscular_id', on_delete=django.db.models.deletion.PROTECT, related_name='ejercicios', to='entrenamiento.grupomuscular')),
            ],
            options={
                'db_table': 'ejercicios',
            },
        ),
        migrations.CreateModel(
            name='RegistroEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('numero_serie', models.SmallIntegerField()),
                ('peso_real', models.DecimalField(decimal_places=2, max_digits=6)),
                ('repeticiones_reales', models.SmallIntegerField()),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros_ejercicios', to='clientes.cliente')),
                ('registrado_por', models.ForeignKey(db_column='registrado_por', on_delete=django.db.models.deletion.PROTECT, related_name='registros_ejercicios', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros_ejercicios', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'registros_ejercicios',
            },
        ),
        migrations.CreateModel(
            name='RecordPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('repeticiones', models.SmallIntegerField()),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='records_personales', to='clientes.cliente')),
                ('ejercicio', models.ForeignKey(db_column='ejercicio_id', on_delete=django.db.models.deletion.PROTECT, related_name='records_personales', to='entrenamiento.ejercicio')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='records_personales', to='plataforma.tenant')),
                ('registro_ejercicio', models.ForeignKey(blank=True, db_column='registro_ejercicio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_personales', to='entrenamiento.registroejercicio')),
            ],
            options={
                'db_table': 'records_personales',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='clientes.cliente')),
                ('entrenador', models.ForeignKey(db_column='entrenador_id', on_delete=django.db.models.deletion.PROTECT, related_name='rutinas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'rutinas',
            },
        ),
        migrations.CreateModel(
            name='RutinaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField()),
                ('nombre', models.CharField(max_length=80)),
                ('rutina', models.ForeignKey(db_column='rutina_id', on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='entrenamiento.rutina')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='rutina_dias', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'rutina_dias',
            },
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.SmallIntegerField()),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('series', models.SmallIntegerField()),
                ('repeticiones', models.SmallIntegerField()),
                ('descanso_segundos', models.SmallIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(db_column='ejercicio_id', on_delete=django.db.models.deletion.PROTECT, related_name='rutina_ejercicios', to='entrenamiento.ejercicio')),
                ('rutina_dia', models.ForeignKey(db_column='rutina_dia_id', on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='entrenamiento.rutinadia')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='rutina_ejercicios', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'rutina_ejercicios',
            },
        ),
        migrations.AddField(
            model_name='registroejercicio',
            name='rutina_ejercicio',
            field=models.ForeignKey(db_column='rutina_ejercicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='entrenamiento.rutinaejercicio'),
        ),
        migrations.AddConstraint(
            model_name='fichamedidas',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_ficha_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='fichamedidas',
            constraint=models.CheckConstraint(condition=models.Q(('estatura_cm__isnull', True), models.Q(('estatura_cm__gte', 80), ('estatura_cm__lte', 260)), _connector='OR'), name='ck_ficha_estatura'),
        ),
        migrations.AddConstraint(
            model_name='fichamedidas',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('cliente',), name='uq_ficha_cliente_activa'),
        ),
        migrations.AddIndex(
            model_name='controlmedida',
            index=models.Index(fields=['ficha_medida', '-fecha'], name='ix_control_ficha_fecha'),
        ),
        migrations.AddConstraint(
            model_name='controlmedida',
            constraint=models.UniqueConstraint(fields=('ficha_medida', 'numero_control'), name='uq_control_numero'),
        ),
        migrations.AddConstraint(
            model_name='controlmedida',
            constraint=models.CheckConstraint(condition=models.Q(('numero_control__gt', 0)), name='ck_control_numero'),
        ),
        migrations.AddConstraint(
            model_name='controlmedida',
            constraint=models.CheckConstraint(condition=models.Q(('edad__isnull', True), models.Q(('edad__gte', 5), ('edad__lte', 120)), _connector='OR'), name='ck_control_edad'),
        ),
        migrations.AddConstraint(
            model_name='controlmedida',
            constraint=models.CheckConstraint(condition=models.Q(('peso_kg__isnull', True), models.Q(('peso_kg__gte', 20), ('peso_kg__lte', 400)), _connector='OR'), name='ck_control_peso'),
        ),
        migrations.AddConstraint(
            model_name='controlmedida',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cuello__isnull', True), ('cuello__gt', 0), _connector='OR'), models.Q(('hombros__isnull', True), ('hombros__gt', 0), _connector='OR'), models.Q(('pecho_espalda__isnull', True), ('pecho_espalda__gt', 0), _connector='OR'), models.Q(('brazos__isnull', True), ('brazos__gt', 0), _connector='OR'), models.Q(('antebrazos__isnull', True), ('antebrazos__gt', 0), _connector='OR'), models.Q(('muneca__isnull', True), ('muneca__gt', 0), _connector='OR'), models.Q(('abdomen__isnull', True), ('abdomen__gt', 0), _connector='OR'), models.Q(('cintura__isnull', True), ('cintura__gt', 0), _connector='OR'), models.Q(('cadera_gluteos__isnull', True), ('cadera_gluteos__gt', 0), _connector='OR'), models.Q(('piernas_media__isnull', True), ('piernas_media__gt', 0), _connector='OR'), models.Q(('rodillas_arriba__isnull', True), ('rodillas_arriba__gt', 0), _connector='OR'), models.Q(('pantorrillas__isnull', True), ('pantorrillas__gt', 0), _connector='OR'), models.Q(('tobillos__isnull', True), ('tobillos__gt', 0), _connector='OR')), name='ck_control_medidas'),
        ),
        migrations.AddConstraint(
            model_name='grupomuscular',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_grupomusc_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='grupomuscular',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uq_grupomusc_nombre'),
        ),
        migrations.AddIndex(
            model_name='ejercicio',
            index=models.Index(condition=models.Q(('activo', True)), fields=['tenant', 'grupo_muscular'], name='ix_ejercicios_grupo'),
        ),
        migrations.AddConstraint(
            model_name='ejercicio',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_ejercicios_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='ejercicio',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uq_ejercicios_nombre'),
        ),
        migrations.AddConstraint(
            model_name='recordpersonal',
            constraint=models.UniqueConstraint(fields=('cliente', 'ejercicio'), name='uq_records_cliente_ejercicio'),
        ),
        migrations.AddConstraint(
            model_name='recordpersonal',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gte', 0), ('repeticiones__gt', 0)), name='ck_records_valores'),
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(fields=['cliente', '-fecha_inicio'], name='ix_rutinas_cliente'),
        ),
        migrations.AddIndex(
            model_name='rutina',
            index=models.Index(condition=models.Q(('activa', True)), fields=['entrenador'], name='ix_rutinas_entrenador'),
        ),
        migrations.AddConstraint(
            model_name='rutina',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_rutinas_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rutina',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='ck_rutinas_fechas'),
        ),
        migrations.AddConstraint(
            model_name='rutinadia',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_rutdia_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rutinadia',
            constraint=models.UniqueConstraint(fields=('rutina', 'numero'), name='uq_rutdia_numero'),
        ),
        migrations.AddConstraint(
            model_name='rutinadia',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='ck_rutdia_numero'),
        ),
        migrations.AddConstraint(
            model_name='rutinaejercicio',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_rutejer_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rutinaejercicio',
            constraint=models.UniqueConstraint(fields=('rutina_dia', 'orden'), name='uq_rutejer_orden'),
        ),
        migrations.AddConstraint(
            model_name='rutinaejercicio',
            constraint=models.CheckConstraint(condition=models.Q(('repeticiones__gt', 0), ('series__gt', 0)), name='ck_rutejer_series'),
        ),
        migrations.AddConstraint(
            model_name='rutinaejercicio',
            constraint=models.CheckConstraint(condition=models.Q(('peso_kg__isnull', True), ('peso_kg__gte', 0), _connector='OR'), name='ck_rutejer_peso'),
        ),
        migrations.AddConstraint(
            model_name='rutinaejercicio',
            constraint=models.CheckConstraint(condition=models.Q(('descanso_segundos__isnull', True), models.Q(('descanso_segundos__gte', 0), ('descanso_segundos__lte', 3600)), _connector='OR'), name='ck_rutejer_descanso'),
        ),
        migrations.AddIndex(
            model_name='registroejercicio',
            index=models.Index(fields=['cliente', '-fecha'], name='ix_regejer_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='registroejercicio',
            index=models.Index(fields=['rutina_ejercicio', '-fecha'], name='ix_regejer_rutejer'),
        ),
        migrations.AddConstraint(
            model_name='registroejercicio',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_regejer_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='registroejercicio',
            constraint=models.UniqueConstraint(fields=('rutina_ejercicio', 'fecha', 'numero_serie'), name='uq_regejer_serie'),
        ),
        migrations.AddConstraint(
            model_name='registroejercicio',
            constraint=models.CheckConstraint(condition=models.Q(('numero_serie__gt', 0), ('peso_real__gte', 0), ('repeticiones_reales__gt', 0)), name='ck_regejer_valores'),
        ),
    ]
