# Generated by Django 6.0.7 on 2026-07-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('pk', models.CompositePrimaryKey('id', 'fecha_hora', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.BigIntegerField()),
                ('tenant_id', models.BigIntegerField()),
                ('usuario_id', models.BigIntegerField(blank=True, null=True)),
                ('usuario_plataforma_id', models.BigIntegerField(blank=True, null=True)),
                ('sede_id', models.BigIntegerField(blank=True, null=True)),
                ('entidad', models.CharField(max_length=60)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('anular', 'Anular'), ('eliminar', 'Eliminar'), ('autorizar', 'Autorizar'), ('login', 'Login'), ('impersonar', 'Impersonar')], max_length=20)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaCorteDiario',
            fields=[
                ('pk', models.CompositePrimaryKey('tenant_id', 'sede_id', 'fecha', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField()),
                ('sede_id', models.BigIntegerField()),
                ('fecha', models.DateField()),
                ('ingreso_ventas', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ingreso_otros', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('transferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'v_corte_diario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaMembresiaEstado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField()),
                ('sede_id', models.BigIntegerField()),
                ('cliente_id', models.BigIntegerField()),
                ('plan_id', models.BigIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_restantes', models.IntegerField()),
                ('estado_calculado', models.CharField(choices=[('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('vence_hoy', 'Vence hoy'), ('por_vencer', 'Por vencer'), ('activa', 'Activa')], max_length=20)),
            ],
            options={
                'db_table': 'v_membresias_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaVentaSaldo',
            fields=[
                ('venta_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField()),
                ('sede_id', models.BigIntegerField()),
                ('cliente_id', models.BigIntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'v_ventas_saldo',
                'managed': False,
            },
        ),
    ]
