# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('precio_por_sede', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ciclo', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], db_default='mensual', max_length=20)),
                ('max_sedes', models.SmallIntegerField(blank=True, null=True)),
                ('max_usuarios', models.SmallIntegerField(blank=True, null=True)),
                ('max_clientes_activos', models.IntegerField(blank=True, null=True)),
                ('max_almacenamiento_mb', models.IntegerField(blank=True, null=True)),
                ('caracteristicas', models.JSONField(db_default={})),
                ('activo', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
            ],
            options={
                'db_table': 'planes_suscripcion',
                'constraints': [models.CheckConstraint(condition=models.Q(('precio_por_sede__gte', 0)), name='ck_planes_susc_precio'), models.CheckConstraint(condition=models.Q(models.Q(('max_sedes__gt', 0), ('max_sedes__isnull', True), _connector='OR'), models.Q(('max_usuarios__gt', 0), ('max_usuarios__isnull', True), _connector='OR'), models.Q(('max_clientes_activos__gt', 0), ('max_clientes_activos__isnull', True), _connector='OR')), name='ck_planes_susc_limites')],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_publico', models.UUIDField(db_default=models.Func(function='gen_random_uuid'), editable=False, help_text='Identificador expuesto en API y URLs; evita enumerar tenants por id secuencial.', unique=True)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('nit', models.CharField(blank=True, max_length=30, null=True)),
                ('subdominio', models.CharField(max_length=41)),
                ('responsable', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('prueba', 'Prueba'), ('activo', 'Activo'), ('mora', 'Mora'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], db_default='prueba', max_length=20)),
                ('zona_horaria', models.CharField(db_default='America/Bogota', max_length=50)),
                ('moneda', models.CharField(db_default='COP', max_length=3)),
                ('dias_aviso_vencimiento', models.SmallIntegerField(db_default=5)),
                ('minutos_antipassback', models.SmallIntegerField(db_default=60)),
                ('fecha_alta', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('fecha_purga_datos', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
            ],
            options={
                'db_table': 'tenants',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('subdominio'), name='uq_tenants_subdominio'), models.CheckConstraint(condition=models.Q(('subdominio__regex', '^[a-z0-9][a-z0-9-]{1,40}$')), name='ck_tenants_subdominio'), models.CheckConstraint(condition=models.Q(('dias_aviso_vencimiento__gte', 0), ('dias_aviso_vencimiento__lte', 60)), name='ck_tenants_dias_aviso'), models.CheckConstraint(condition=models.Q(('minutos_antipassback__gte', 0), ('minutos_antipassback__lte', 1440)), name='ck_tenants_antipass'), models.CheckConstraint(condition=models.Q(('fecha_purga_datos__isnull', True), models.Q(('fecha_cancelacion__isnull', False), ('fecha_purga_datos__gt', models.F('fecha_cancelacion'))), _connector='OR'), name='ck_tenants_purga')],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('proximo_corte', models.DateField()),
                ('dias_gracia', models.SmallIntegerField(db_default=5)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('mora', 'Mora'), ('cancelada', 'Cancelada')], db_default='vigente', max_length=20)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('plan_suscripcion', models.ForeignKey(db_column='plan_suscripcion_id', on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='plataforma.plansuscripcion')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'suscripciones',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=254)),
                ('password_hash', models.TextField()),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('soporte', 'Soporte')], max_length=20)),
                ('activo', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
            ],
            options={
                'db_table': 'usuarios_plataforma',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('correo'), name='uq_usuarios_plataforma_correo')],
            },
        ),
        migrations.CreateModel(
            name='Impersonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('autorizado_por', models.CharField(max_length=150)),
                ('inicio', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='impersonaciones', to='plataforma.tenant')),
                ('usuario_plataforma', models.ForeignKey(db_column='usuario_plataforma_id', on_delete=django.db.models.deletion.PROTECT, related_name='impersonaciones', to='plataforma.usuarioplataforma')),
            ],
            options={
                'db_table': 'impersonaciones',
            },
        ),
        migrations.CreateModel(
            name='FacturaSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('sedes_facturadas', models.SmallIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], db_default='emitida', max_length=20)),
                ('fecha_emision', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('suscripcion', models.ForeignKey(db_column='suscripcion_id', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='plataforma.suscripcion')),
            ],
            options={
                'db_table': 'facturas_suscripcion',
                'constraints': [models.UniqueConstraint(fields=('suscripcion', 'periodo_inicio'), name='uq_facturas_periodo'), models.CheckConstraint(condition=models.Q(('periodo_fin__gt', models.F('periodo_inicio'))), name='ck_facturas_periodo'), models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ck_facturas_monto'), models.CheckConstraint(condition=models.Q(('sedes_facturadas__gt', 0)), name='ck_facturas_sedes'), models.CheckConstraint(condition=models.Q(models.Q(('estado', 'pagada'), ('fecha_pago__isnull', False)), models.Q(models.Q(('estado', 'pagada'), _negated=True), ('fecha_pago__isnull', True)), _connector='OR'), name='ck_facturas_pago')],
            },
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=['proximo_corte'], name='ix_suscripciones_corte'),
        ),
        migrations.AddConstraint(
            model_name='suscripcion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='ck_suscripciones_fechas'),
        ),
        migrations.AddConstraint(
            model_name='suscripcion',
            constraint=models.CheckConstraint(condition=models.Q(('dias_gracia__gte', 0), ('dias_gracia__lte', 90)), name='ck_suscripciones_gracia'),
        ),
        migrations.AddConstraint(
            model_name='suscripcion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'vigente')), fields=('tenant',), name='uq_suscripciones_vigente'),
        ),
        migrations.AddIndex(
            model_name='impersonacion',
            index=models.Index(fields=['tenant', '-inicio'], name='ix_imperson_tenant'),
        ),
        migrations.AddConstraint(
            model_name='impersonacion',
            constraint=models.CheckConstraint(condition=models.Q(('fin__isnull', True), ('fin__gte', models.F('inicio')), _connector='OR'), name='ck_imperson_fin'),
        ),
    ]
