# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('fecha_registro', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('activo', models.BooleanField(db_default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('sede_origen', models.ForeignKey(db_column='sede_origen_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientes_origen', to='organizacion.sede')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='AutorizacionDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tratamiento_datos', 'Tratamiento de datos'), ('biometria', 'Biometría')], max_length=20)),
                ('otorgada', models.BooleanField()),
                ('fecha', models.DateField(db_default=models.Func(function='CURRENT_DATE', template='%(function)s'))),
                ('archivo_firmado_url', models.TextField(blank=True, null=True)),
                ('revocada_en', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_datos', to='plataforma.tenant')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='clientes.cliente')),
            ],
            options={
                'db_table': 'autorizaciones_datos',
            },
        ),
        migrations.CreateModel(
            name='DispositivoBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('identificador', models.CharField(max_length=120)),
                ('modelo', models.CharField(db_default='ZKTeco ZK9500', max_length=60)),
                ('token_hash', models.TextField()),
                ('activo', models.BooleanField(db_default=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_biometricos', to='organizacion.sede')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_biometricos', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'dispositivos_biometricos',
            },
        ),
        migrations.CreateModel(
            name='HuellaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedo', models.CharField(choices=[('indice_izquierdo', 'Índice izquierdo'), ('indice_derecho', 'Índice derecho'), ('pulgar_izquierdo', 'Pulgar izquierdo'), ('pulgar_derecho', 'Pulgar derecho'), ('medio_izquierdo', 'Medio izquierdo'), ('medio_derecho', 'Medio derecho')], max_length=20)),
                ('plantilla_cifrada', models.BinaryField()),
                ('calidad', models.SmallIntegerField()),
                ('formato', models.CharField(db_default='ZKFinger10', max_length=30)),
                ('fecha_captura', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='huellas', to='clientes.cliente')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='huellas_clientes', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'huellas_clientes',
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(condition=models.Q(('eliminado_en__isnull', True)), fields=['tenant', 'cedula'], name='ix_clientes_cedula'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(condition=models.Q(('activo', True), ('eliminado_en__isnull', True)), fields=['tenant'], name='ix_clientes_activos'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_clientes_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('tenant', 'cedula'), name='uq_clientes_cedula'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('sexo__isnull', True), ('sexo__in', ['M', 'F', 'O']), _connector='OR'), name='ck_clientes_sexo'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('cedula__regex', '^[0-9A-Za-z.-]{4,20}$')), name='ck_clientes_cedula'),
        ),
        migrations.AddConstraint(
            model_name='autorizaciondatos',
            constraint=models.UniqueConstraint(fields=('cliente', 'tipo'), name='uq_autoriz_cliente_tipo'),
        ),
        migrations.AddConstraint(
            model_name='dispositivobiometrico',
            constraint=models.UniqueConstraint(fields=('tenant', 'identificador'), name='uq_dispositivos_ident'),
        ),
        migrations.AddIndex(
            model_name='huellacliente',
            index=models.Index(fields=['cliente'], name='ix_huellas_cliente'),
        ),
        migrations.AddConstraint(
            model_name='huellacliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'dedo'), name='uq_huellas_cliente_dedo'),
        ),
        migrations.AddConstraint(
            model_name='huellacliente',
            constraint=models.CheckConstraint(condition=models.Q(('calidad__gte', 0), ('calidad__lte', 100)), name='ck_huellas_calidad'),
        ),
    ]
