"""
Django settings for config project (base / common settings).

Generated by 'django-admin startproject' using Django 6.0.7, later split
into base/dev/prod modules.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# NOTE: este módulo vive en config/settings/base.py, un nivel más profundo
# que el antiguo config/settings.py, así que hace falta un `.parent` extra
# para que BASE_DIR siga apuntando a `backend/`.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Lee variables de entorno desde backend/.env
environ.Env.read_env(BASE_DIR / '.env')


# SECURITY WARNING: keep the secret key used in production secret!
# Sin valor por defecto: si falta DJANGO_SECRET_KEY en el entorno, debe
# reventar en lugar de arrancar con una clave insegura.
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'apps.plataforma',
    'apps.organizacion',
    'apps.autenticacion',
    'apps.clientes',
    'apps.membresias',
    'apps.inventario',
    'apps.ventas',
    'apps.asistencia',
    'apps.entrenamiento',
    'apps.auditoria',
    'apps.core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # TenantMiddleware va DESPUÉS de AuthenticationMiddleware porque en el
    # futuro (fuera del alcance de esta etapa) la resolución de tenant podría
    # apoyarse en request.user; y va ANTES de cualquier middleware propio de
    # la aplicación porque abre la transacción que fija app.tenant_id para
    # RLS (ver apps/core/middleware.py) y esa transacción debe envolver toda
    # la cadena restante, incluida la vista.
    'apps.core.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Rutas que funcionan sin tenant resuelto: el middleware no abre transacción
# de tenant para ellas. Deben ser accesibles antes de que el cliente sepa (o
# pueda demostrar) a qué gimnasio pertenece: registro, refresco de token y
# logout de la API, además de los estáticos.
#
# Parte C1: '/admin/' (a secas) SALIÓ deliberadamente de esta lista. Antes de
# la Parte C el admin no servía a usuarios de tenant (is_staff/is_superuser
# eran siempre False) y no tenía sentido abrirle una transacción de tenant;
# ahora sí, así que el resto del admin (listados, formularios...) debe pasar
# por la misma resolución de tenant + RLS que cualquier otra ruta de negocio.
#
# '/admin/login/' y '/api/auth/login/' TAMPOCO están exentas, a pesar de que
# el usuario todavía no se ha autenticado cuando las visita -- y esto es
# DELIBERADO, no un descuido: ambas disparan un login real
# (`django.contrib.auth.login()` en el caso del admin), que emite la señal
# `user_logged_in` -> `update_last_login()` -> un UPDATE sobre `usuarios`
# (RLS con FORCE). Si esa ruta estuviera exenta, el middleware NO abriría
# tenant_context alrededor de la vista y ese UPDATE fallaría siempre (0 filas
# afectadas, `Usuario.NotUpdated`) -- se comprobó en vivo, es un fallo real,
# no hipotético. Al dejarla SIN exención, cuando el subdominio resuelve un
# tenant (el caso normal: se entra por `<subdominio>.tuapp.com/admin/login/`
# o el body de /api/auth/login/ no lleva tenant pero el Host sí), el
# middleware abre tenant_context para TODA la petición -- incluida esta
# escritura -- y la vista de login queda cubierta igual que cualquier otra.
# Cuando el subdominio NO resuelve ningún tenant, el middleware sigue
# funcionando: `if tenant is None: return self.get_response(request)` (más
# abajo) dispensa la petición sin abrir transacción, así que la página de
# login renderiza igual y un POST sin tenant simplemente falla limpio con
# credenciales inválidas (falla cerrado), sin necesitar una exención.
TENANT_EXEMPT_PATHS = [
    '/static/',
    '/api/auth/register/',
    '/api/auth/refresh/',
    '/api/auth/logout/',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Dos conexiones:
#   - 'default': runtime de la aplicación. Rol SIN privilegios (keradmin):
#     Row Level Security lo somete de verdad. Nunca debe apuntar a un
#     superusuario, porque los superusuarios ignoran RLS incluso con
#     FORCE ROW LEVEL SECURITY.
#   - 'ddl': solo para DDL (migrate, makemigrations, creación de la BD de
#     tests). Es superusuario, así que jamás debe usarse para servir
#     peticiones.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_APP_USER'),
        'PASSWORD': env('DB_APP_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    },
    'ddl': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_DDL_USER'),
        'PASSWORD': env('DB_DDL_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        # Evita que el test runner intente crear una segunda base de datos
        # de prueba: la refleja sobre 'default'.
        'TEST': {'MIRROR': 'default'},
    },
}

# Necesario para que `SET LOCAL app.tenant_id` (usado por las políticas RLS)
# funcione correctamente: cada request debe ejecutarse dentro de una única
# transacción, para que el SET LOCAL siga vigente durante toda la petición.
DATABASES['default']['ATOMIC_REQUESTS'] = True
DATABASES['ddl']['ATOMIC_REQUESTS'] = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Modelo de usuario personalizado
# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = 'organizacion.Usuario'

# auth.W004 advierte que USERNAME_FIELD ('correo') no tiene unique=True a
# nivel de Django. Es deliberado: el correo es único POR TENANT
# (UniqueConstraint(Lower('correo'), 'tenant')), NO globalmente -- ese es el
# requisito de negocio (la misma persona puede trabajar en dos gimnasios
# clientes con el mismo correo). Un unique=True global en la columna
# rompería justamente ese caso, así que el warning se silencia a propósito
# en vez de "corregirlo".
SILENCED_SYSTEM_CHECKS = ['auth.W004']

# Backend de autenticación consciente del tenant (Parte B, movido a su propia
# app en la Parte A). Reemplaza por completo al ModelBackend por defecto:
# aquí "correo" no es único globalmente, así que resolver un usuario requiere
# primero un tenant (ver apps/autenticacion/backends.py).
AUTHENTICATION_BACKENDS = [
    'apps.autenticacion.backends.TenantAuthBackend',
]


# Django REST Framework
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Parte D (ventas/POS): todo listado de la API debe venir paginado.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# CORS (django-cors-headers)
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
    'http://127.0.0.1:4200',
]
