# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(blank=True, max_length=80, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=60, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo', models.DecimalField(db_default=0, decimal_places=2, max_digits=12)),
                ('stock_minimo', models.DecimalField(db_default=0, decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(db_default=True)),
                ('creado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='StockSede',
            fields=[
                # Sin `pk` (CompositePrimaryKey) aquí a propósito: el modelo
                # real usa PK compuesta (producto_id, sede_id), pero esas dos
                # FK todavía no existen en este punto de la migración (se
                # añaden en 0002_initial, después de que exista `Producto`
                # -- dependencia circular producto<->stock_sedes resuelta
                # por el propio autodetector de Django dividiendo en dos
                # migraciones). Declarar aquí la CompositePrimaryKey
                # reventaría con FieldDoesNotExist. Se usa un `id` AutoField
                # implícito temporal; la migración
                # apps.inventario.0003_stock_sedes_pk_compuesta corrige el
                # ESTADO (no la base real, que la crea directamente con la
                # PK compuesta apps.core.0001_esquema_postgres) una vez que
                # 'producto' y 'sede' ya existen.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(db_default=0, decimal_places=2, max_digits=12)),
                ('actualizado_en', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
            ],
            options={
                'db_table': 'stock_sedes',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('activa', models.BooleanField(db_default=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='categorias_producto', to='plataforma.tenant')),
            ],
            options={
                'db_table': 'categorias_producto',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada por compra'), ('salida_venta', 'Salida por venta'), ('ajuste_manual', 'Ajuste manual'), ('reverso_anulacion', 'Reverso por anulación')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_resultante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(db_default=models.Func(function='clock_timestamp'))),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='organizacion.sede')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='plataforma.tenant')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimientos_inventario',
            },
        ),
    ]
