# Generated by Django 6.0.7 on 2026-07-30 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('plataforma', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, db_column='venta_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_producto',
            field=models.ForeignKey(db_column='categoria_producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='plataforma.tenant'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='stocksede',
            name='producto',
            field=models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_sedes', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='stocksede',
            name='sede',
            field=models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_productos', to='organizacion.sede'),
        ),
        migrations.AddField(
            model_name='stocksede',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_sedes', to='plataforma.tenant'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproducto',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_catprod_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproducto',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uq_catprod_nombre'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='uq_productos_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre', 'marca', 'presentacion'), name='uq_productos_nombre'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras__isnull', False)), fields=('tenant', 'codigo_barras'), name='uq_productos_barras'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gte', 0)), name='ck_productos_precio'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('costo__gte', 0)), name='ck_productos_costo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='ck_productos_stockmin'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'sede', '-fecha_hora'], name='ix_movinv_producto_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tenant', '-fecha_hora'], name='ix_movinv_tenant_fecha'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='ck_movinv_cantidad'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'ajuste_manual'), _negated=True), models.Q(('motivo__isnull', False), models.Q(('motivo__regex', '^\\s*$'), _negated=True)), _connector='OR'), name='ck_movinv_motivo'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cantidad__gt', 0), ('tipo__in', ['entrada_compra', 'reverso_anulacion'])), models.Q(('cantidad__lt', 0), ('tipo', 'salida_venta')), ('tipo', 'ajuste_manual'), _connector='OR'), name='ck_movinv_signo'),
        ),
        migrations.AddConstraint(
            model_name='stocksede',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='ck_stock_cantidad'),
        ),
        # Constraint temporal real (no solo de estado): apps.core.0001_esquema
        # _postgres espera poder hacer
        # "ALTER TABLE stock_sedes DROP CONSTRAINT pk_stock_sedes" para
        # sustituirlo por la PK compuesta real (producto_id, sede_id). Se
        # crea aquí, ahora que 'producto' y 'sede' ya existen como columnas,
        # y se retira del ESTADO (no de la base, que ya la reemplazó la
        # migración de esquema) en
        # apps.inventario.0003_stock_sedes_pk_compuesta.
        migrations.AddConstraint(
            model_name='stocksede',
            constraint=models.UniqueConstraint(fields=('producto', 'sede'), name='pk_stock_sedes'),
        ),
    ]
